spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: example
      properties:
        spring.json.trusted.packages: com.example.kafka.application.message
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        max.poll.interval.ms: 600000
        session.timeout.ms: 100000
      max-poll-records: 10
      enable-auto-commit: true
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false
  batch:
    job:
      names: ${job.name:originalDlqJob}
    jdbc:
      initialize-schema: always
